# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed203534d486f90ed7e5c69c0ddd1b980750658e40790e1b00cb65f33538bcf512ecd70200b090459f34c0227f5efb683e37eb39c26ad9f7c942d5d15afdb1e

test:
  secret_key_base: 2477ac48f815ad8b4b866b8b00011a4a1d7c7a39eb5c4bf70f65c7bf6f31bedef6b11ddc6bdcd4b69be0f47b3c882546ba21486a66fcbdd07b402d1368a2e1f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
